import type { Metadata } from 'next';

import { Inter } from 'next/font/google';
import '../globals.css';
import Header from '@components/layout/Header/Header';
import Footer from '@components/layout/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Studio Hackathon',
  description: 'Generated by the Colorful Team!',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
