import type { Metadata } from "next";

import "../globals.css";
import Header from "@components/layout/Header/Header";
import Footer from "@components/layout/Footer/Footer";
import { Inter } from 'next/font/google';
import InteractiveHeader from "../_components/CustomHeader/InteractiveHeader";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Studio Quickstart",
  description: "Generated by the Contentful Team!",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <InteractiveHeader />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
