import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import "../globals.css";
import Header from "@components/layout/Header/Header";
import Footer from "@components/layout/Footer/Footer";

export const metadata: Metadata = {
  title: "Studio Quickstart",
  description: "Generated by the Contentful Team!",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
